###
GET http://localhost:8080/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzEzNzcxMTk3LCJQcm9maWxlIjp7ImlkIjoxLCJuYW1lIjoiam9oYW4iLCJ1c2VybmFtZSI6ImpvaGFuIiwicGhvdG8iOm51bGx9fQ.1Q2I-S6xUu5qVCkDdFyUZ3vOjvNCWOcdKQiLCrc3wvo